const ActionTypes = {
	USER_REGISTER: "USER_REGISTER",
	USER_LOGIN: "USER_LOGIN",
	USER_LOGOUT: "USER_LOGOUT",
	UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
	USER_VERIFICATION: "USER_VERIFICATION",
	SET_USER_DATA: "SET_USER_DATA",
	GET_USER_DATA: "GET_USER_DATA",
	FORGOT_PASSWORD: "FORGOT_PASSWORD",
	RESET_PASSWORD: "RESET_PASSWORD",
};

export default ActionTypes;
